# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_disasm age1xls94zehkupxnvtc5krd3clm4ky28npate5n09cgmzsyjlh6actqmm89xn
  - &admin_adam age1t9nghzw475h87zsne2luj9zf0tvev7rtvaauq5yhhvl8lumwxu9s8hl4g5
  - &hydra-arcade-test age1kyrzwkuss4shyqlckausvyyed47jte75ahdmzl439xwuan2uzghsxfahp2
  - &hydra-arcade-1 age1ffacux409u4t76n43qngqdruuxtcndwheee8mzxen55a3ad4uqnqmqckaa
  - &hydra-arcade-2 age1jmjgnr89j7prfr2cxwpj7mw25hmg2hjq2veg03z0wrtpufqevpssghlcsk
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *admin_disasm
      - *admin_adam
      - *hydra-arcade-test
      - *hydra-arcade-1
      - *hydra-arcade-2
